from cgitb import reset
import numpy as np
import random
import string

upper = string.ascii_uppercase

def fill(s):
    for line in s.split("\n"):
        res = ""
        for c in line:
            if c != ".": res += c.upper()
            else: res += random.choice(upper)
        print(res)

if __name__ == "__main__":
    s = """..b.......
..i..s....
..o..l....
..m..o....
..a..s....
..s..o....
..s..r....
.....e....
.....a....
.........."""
    fill(s)